import { Fira_Code } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
const inter = Fira_Code({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=' flex justify-center items-center flex-col max-w-screen-sm  md:max-w-7xl mx-auto sm:px-16 px-6 '>
        <Header/>

        {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
