import { Fira_Code } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
const inter = Fira_Code({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='width-[1024px] m-auto '>

        <Header/>
        {children}
        </main>
        </body>
    </html>
  )
}
